package com.yulinlin.data.core.wrapper.factory;

import com.yulinlin.data.core.anno.*;
import com.yulinlin.data.core.exception.NoticeException;
import com.yulinlin.data.core.model.BaseModel;
import com.yulinlin.data.core.util.MetaUtil;
import com.yulinlin.data.core.wrapper.IUpdateWrapper;
import com.yulinlin.data.core.wrapper.IConditionWrapper;
import com.yulinlin.data.lang.reflection.AnnotationUtil;
import com.yulinlin.data.lang.reflection.ProxyUtil;
import com.yulinlin.data.lang.reflection.ReflectionUtil;

import java.lang.reflect.Field;
import java.util.*;

/** Builds a partial update without constructing a second entity or executing its setters. */
public final class UpdatePatchFactory {
    private UpdatePatchFactory() { }
    private static final ClassValue<Boolean> UPDATE_HOOK = new ClassValue<>() {
        @Override protected Boolean computeValue(Class<?> type) {
            if (!BaseModel.class.isAssignableFrom(type)) return false;
            try { return type.getMethod("updateBefore").getDeclaringClass() != BaseModel.class; }
            catch (NoSuchMethodException error) { throw new IllegalStateException(error); }
        }
    };

    public static boolean persistent(Field field) {
        JoinField mapping = AnnotationUtil.findAnnotation(field, JoinField.class);
        return (mapping == null || mapping.exist())
                && AnnotationUtil.findAnnotation(field, JoinQuery.class) == null;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public static IUpdateWrapper create(IUpdateWrapper wrapper, Object model, Map<String, Object> dirty,
                                       Map<String, Object> primaryKeys, Map<String, Object> versions) {
        Class<?> type = ProxyUtil.getProxyClass(model.getClass());
        JoinTable table = AnnotationUtil.findAnnotation(type, JoinTable.class);
        if (table == null) throw new NoticeException("缺少JoinTable注解: " + type.getName());
        if (primaryKeys.isEmpty() || primaryKeys.containsValue(null)) throw new NoticeException("懒同步要求完整的非空主键");
        for (var key : primaryKeys.entrySet()) {
            if (!Objects.equals(key.getValue(), ReflectionUtil.invokeGetter(model, key.getKey())))
                throw new NoticeException("懒同步不允许修改主键: " + key.getKey());
        }
        List<Field> fields = ReflectionUtil.getAllDeclaredFields(type);
        Map<String, Object> selected = new HashMap<>(dirty);
        if (UPDATE_HOOK.get(type)) {
            Map<String, Object> beforeHook = new HashMap<>();
            for (Field field : fields) if (persistent(field))
                beforeHook.put(field.getName(), ReflectionUtil.invokeGetter(model, field.getName()));
            EventUtil.before(model, EventUtil.update);
            for (Field field : fields) if (persistent(field)) {
                Object value = ReflectionUtil.invokeGetter(model, field.getName());
                if (!Objects.equals(beforeHook.get(field.getName()), value))
                    selected.put(field.getName(), value); // Preserve values generated by updateBefore().
            }
        }
        wrapper.table(table.value());
        int assignments = 0;
        for (Field field : fields) {
            if (!persistent(field)) continue;
            String name = field.getName();
            JoinField mapping = AnnotationUtil.findAnnotation(field, JoinField.class);
            String column = mapping != null && !mapping.name().isEmpty() ? mapping.name() : name;
            JoinMeta meta = AnnotationUtil.findAnnotation(field, JoinMeta.class);
            if (primaryKeys.containsKey(name)) {
                if (!Objects.equals(primaryKeys.get(name), ReflectionUtil.invokeGetter(model, name)))
                    throw new NoticeException("updateBefore 不允许修改主键: " + name);
                ((IConditionWrapper) wrapper.where()).eq(column, primaryKeys.get(name));
                continue;
            }
            if (versions.containsKey(name)) continue;
            if (!selected.containsKey(name) || (mapping != null && !mapping.update())) continue;
            Object value = selected.get(name);
            if (value == null) continue; // Existing null-skipping semantics are intentional.
            if (meta != null) wrapper.fields().meta(MetaUtil.toMap(meta));
            UpdateTypeEnum operation = mapping == null ? UpdateTypeEnum.set : mapping.updateType();
            if (operation == UpdateTypeEnum.inc) wrapper.fields().inc(column, (Number) value);
            else if (operation == UpdateTypeEnum.dec) wrapper.fields().dec(column, (Number) value);
            else wrapper.fields().field(column, value);
            assignments++;
        }
        if (assignments == 0) return null;
        for (var version : versions.entrySet()) {
            Field field = ReflectionUtil.findField(type, version.getKey());
            JoinField mapping = AnnotationUtil.findAnnotation(field, JoinField.class);
            String column = mapping.name().isEmpty() ? field.getName() : mapping.name();
            ((IConditionWrapper) wrapper.where()).eq(column, version.getValue());
            wrapper.fields().inc(column, 1);
        }
        return wrapper;
    }
}
